[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fairswap = "69hNfSV6nw46VXAJ3ukAQhSXikKdX2L3nP4UkLDEMnrr"
simple_amm = "A1X5VnxNAYpS4zGUsHA5s7rx625qeU8P5EnqnGHeU6jW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
